Public Class clsScheduler
    Public Property val_0 As String
    Public Property val_1 As String
    Public Property val_2 As String
    Public Property val_3 As String
    Public Property val_4 As String
    Public Property val_5 As String
    Public Property val_6 As String
    Public Property val_7 As String
    Public Property val_8 As String
    Public Property val_9 As String
    Public Property val_10 As String
    Public Property val_11 As String
    Public Property val_12 As String
    Public Property val_13 As String
    Public Property val_14 As String
    Public Property val_15 As String
    Public Property val_16 As String
    Public Property val_17 As String
    Public Property val_18 As String
    Public Property val_19 As String
    Public Property val_20 As String
    Public Property val_21 As String
    Public Property val_22 As String
    Public Property val_23 As String
    Public Property val_24 As String
    Public Property val_25 As String
    Public Property val_26 As String
    Public Property val_27 As String
    Public Property val_28 As String
    Public Property val_29 As String
    Public Property val_30 As String
    Public Property val_31 As String
    Public Property val_32 As String
    Public Property val_33 As String
    Public Property val_34 As String
    Public Property val_35 As String
    Public Property val_36 As String
    Public Property val_37 As String
    Public Property val_38 As String
    Public Property val_39 As String
    Public Property val_40 As String
    Public Property val_41 As String
    Public Property val_42 As String
    Public Property val_43 As String
    Public Property val_44 As String
    Public Property val_45 As String
    Public Property val_46 As String
    Public Property val_47 As String
    Public Property val_48 As String
    Public Property val_49 As String
    Public Property val_50 As String
End Class
